config/routes.rb
Rails.application.routes.draw do

  root "users#index"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show] 

  namespace :user do
    resources :favorites
  end

  resources :categories, only: [:index, :show]

  namespace :admin do
    resources :categories, only: [:index, :new, :create, :show, :destroy] do
      resources :gifs, only: [:create, :show, :destroy]
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validate :no_white_space
  has_many :gifs

  def no_white_space
    if name.nil?
    elsif name.chars.include?(" ")
      errors.add(:name, "has to be one word and cannot have a space.")
    end
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :gif
  belongs_to :user
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  validates :url_path, presence: true
  belongs_to :category
  has_many :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
  validates :role, presence: true
  validate :no_white_space
  has_many :favorites
  has_many :gifs, through: :favorites
  
  enum role: %w(default admin)

  def no_white_space
    if username.nil?
    elsif username.chars.include?(' ')
      errors.add(:username, "cannot have any spaces.")
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_category_path(@category)
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/gifs_controller.rb
class Admin::GifsController < Admin::BaseController

  def create
    @category = Category.find(params[:category_id])
    url = create_url_path(@category.name)
    gif_data = generate_gif(url)['data'].first
    image = gif_data['images']['original']['url']
    small_image = gif_data['images']['fixed_height_small']['url']
    url_path = gif_data['url']
    name = gif_data['slug']
    bitly = gif_data['bitly_url']
    @gif = @category.gifs.new(url_path: url_path, image: image, name: name, bitly: bitly, small_image: small_image)
    if @gif.save
      redirect_to admin_category_gif_path(@category, @gif)
    else
      redirect_to @category
    end
  end

  def show
    @gif = Gif.find(params[:id])
  end

  def destroy
    gif = Gif.find(params[:id]).destroy
    flash[:notice] = "Article #{gif.name} was deleted"
    redirect_to admin_category_path(gif.category)
  end

end

app/controllers/application_controller.rb
require 'net/http'
require 'json'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?, :generate_gif

  def current_admin?
     User.find(session[:user_id]).role == "admin" if session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def create_url_path(category)
    "http://api.giphy.com/v1/gifs/search?q=" + "#{category}" + "&api_key=dc6zaTOxFJmzC&limit=5"
  end

  def generate_gif(url_path)
    resp = Net::HTTP.get_response(URI.parse(url_path))
    buffer = resp.body
    result = JSON.parse(buffer)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_action :require_user

  def require_user
    render file: "/public/404" unless current_user
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < User::BaseController

  def index
    @categories = User.find(params[:favorite_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/admin/categories/index.html.erb
<h1>Admin Categories Page</h1>

<h3><%= link_to "Create A New Category", new_admin_category_path %></h3>

<h1>All Categories</h1>

<ul>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, admin_category_path(category) %> -
      <%= link_to "Delete", admin_category_path(category), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render partial: 'shared/errors', locals: { target: @category } %>

<p>
  Categories are one word and must be unique...
</p>
<%= form_for [:admin, @category] do |f| %>
  <%= f.text_field :name, placeholder: "Category Name" %>
  <%= f.submit "Create" %>
<% end %>

app/views/admin/categories/show.html.erb
<h1>Gif's for <%= @category.name %></h1>
<p>
  <%= link_to "Delete Category", admin_category_path(@category), method: :delete %>
</p>
<h2><%= link_to "Generate Gif", admin_category_gifs_path(@category), method: :post  %></h2>

<div class="row">
    <%= @category.gifs.each do |gif| %>
    <p>
      <img src="<%= gif.small_image %>" alt="<%= gif.url_path %>" />
      <%= link_to "View Gif", admin_category_gif_path(gif.category, gif) %>
    </p>
    <% end %>
</div>

app/views/admin/gifs/show.html.erb
<h1>Gif: <%= @gif.name %></h1>
<h3><%= link_to "Delete", admin_category_gif_path(@gif.category, @gif), method: :delete %></h3>
<p>
  Link URL: <%= @gif.url_path %>
</p>
<p>
  Bitly: <%= @gif.bitly %>
</p>

<img src="<%= @gif.image %>" alt="<%= @gif.url_path %>" />

app/views/categories/show.html.erb
<h1>Gif's for <%= @category.name %></h1>

<div class="row">
    <%= @category.gifs.each do |gif| %>
    <p>
      <img src="<%= gif.small_image %>" alt="<%= gif.url_path %>" />
      <%= link_to "View Gif", category_gif_path(gif.category, gif) %>
    </p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: 'shared/navbar' %>
  
<!-- <div class="row">
  <div class="logo">
    <% if current_user && current_admin? %>
    <h1>Welcome, <%= current_user.name %>! This is the Admin Page.</h1>
    <% elsif current_user %>
    <h1>Welcome, <%= current_user.name %>!</h1>
    <% end %>
  </div>
  <div class="">

  </div>
</div> -->



<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
    <% target.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <a class="navbar-brand" href="<%= root_path %>">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user && current_admin? %>

        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="<%= admin_categories_path %>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li role="separator" class="divider"></li>
                <li><a href="<%= admin_categories_path %>">All</a></li>
                <li role="separator" class="divider"></li>
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", admin_category_path(category) %></li>
              <% end %>
            </ul>
          </li>
        </ul>

      <% elsif current_user && !current_admin?%>

          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="<%= categories_path %>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li role="separator" class="divider"></li>
                  <li><a href="<%= categories_path %>">All</a></li>
                  <li role="separator" class="divider"></li>
                <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category) %></li>
                <% end %>
              </ul>
            </li>

            <li class="dropdown">
              <a href="<%= user_favorites_path %>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Favorites <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li role="separator" class="divider"></li>
                  <li><a href="<%= user_favorites_path(current_user) %>">All</a></li>
                  <li role="separator" class="divider"></li>
                <% User.find(current_user.id).gifs.all.each do |gif| %>
                  <li><%= link_to "#{gif.category.name}", user_category_path(gif.category) %></li>
                <% end %>
              </ul>
            </li>

        </ul>

      <% end %>

    </div><!-- /.navbar-collapse -->
    <% if current_user && current_admin? %>
      <h5>Welcome, <%= current_user.name %>! This is the Admin Portal. <%= link_to "Logout", logout_path, method: :delete %></h5>
    <% elsif current_user %>
      <h5>Welcome, <%= current_user.name %>! <%= link_to "Logout", logout_path, method: :delete %></h5>
    <% end %>
  </div><!-- /.container-fluid -->
</nav>

app/views/user/index.html.erb
<h1>Favorites Categoris</h1>

app/views/users/index.html.erb
<h1>Welcome to Gif Generator</h1>

<h2><%= link_to "Create New User", new_user_path %></h2>
<h2><%= link_to "Log In", login_path %></h2>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= render partial: 'shared/errors', locals: { target: @user } %>

<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: "First Name" %>
  <%= f.text_field :username, placeholder: "Username" %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
  <%= f.submit "Create New User" %>
<% end %>